#!/bin/bash
export NODE_OPTIONS=--max-old-space-size=32768
jupyter labextension install @jupyter-widgets/jupyterlab-manager > /dev/null 2>&1 || echo "Extension failed to install:  @jupyter-widgets/jupyterlab-manager"
jupyter labextension install jupyterlab_toc > /dev/null 2>&1 || echo "Extension failed to install: jupyterlab_toc"
jupyter labextension install jupyterlab_iframe > /dev/null 2>&1 || echo "Extension failed to install: jupyterlab_iframe"
jupyter labextension install jupyterlab_html > /dev/null 2>&1 || echo "Extension failed to install: jupyterlab_html"
jupyter labextension install jupyterlab_commands > /dev/null 2>&1 || echo "Extension failed to install: jupyterlab_commands"
jupyter labextension install jupyterlab_templates > /dev/null 2>&1 || echo "Extension failed to install: jupyterlab_templates"
jupyter labextension install jupyterlab-drawio > /dev/null 2>&1 || echo "Extension failed to install: jupyterlab-drawio"
jupyter labextension install jupyterlab_voyager > /dev/null 2>&1 || echo "Extension failed to install: jupyterlab_voyager"
jupyter labextension install jupyterlab_monaco > /dev/null 2>&1 || echo "Extension failed to install: jupyterlab_monaco"
jupyter labextension install @jupyterlab/plotly-extension > /dev/null 2>&1 || echo "Extension failed to install: @jupyterlab/plotly-extension"
# jupyter labextension install plotlywidget > /dev/null 2>&1 || echo "Extension failed to install: @jupyterlab/plotly-extension"
jupyter labextension install jupyterlab_bokeh > /dev/null 2>&1 || echo "Extension failed to install: jupyterlab_bokeh"
jupyter labextension install bqplot > /dev/null 2>&1 || echo "Extension failed to install: bqplot"
jupyter labextension install qgrid > /dev/null 2>&1 || echo "Extension failed to install: qgrid"
jupyter labextension install @oriolmirosa/jupyterlab_materialdarker > /dev/null 2>&1 || echo "Extension failed to install: @oriolmirosa/jupyterlab_materialdarker"
jupyter labextension install @jpmorganchase/perspective-jupyterlab > /dev/null 2>&1 || echo "Extension failed to install: @jpmorganchase/perspective-jupyterlab"
